language: node_js

node_js: – 16.0.0

script: cd docs && vercel --prod --token $TRAVIS_TEST

before_script:
  - echo before script
  - npm i -g vercel
  - VERCEL_ORG_ID=$VERCEL_ORG_ID VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID vercel --token $TRAVIS_TEST

after_script:
  - echo after script
  - echo yeah! success!

cache:
  directories: – node_modules
